### ISSUE TITLE
[Design] 반응형 디테일 수정

### ISSUE THREAD

**Issue by simeunseo** [goormthon-Univ/goormthon_univ#58]
## 🛠 Issue

반응형 놓친 부분을 수정합니다.

## 📝 To-do

- [x] goal 섹션 height 조정
- [x] intro 섹션 작은 텍스트 추가
- [x] benefit 섹션 작은 텍스트 분기 수정
- [x] findingUniv 섹션 작은 텍스트 추가
